{"uuid": "2eaa19d9-2297-4c77-8615-18fdf1704022", "children": ["95443aea-381c-4650-bf2b-ba5be0cb1162"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.rzmwzc.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002C0812379C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\Atest_project\\requests_pytest_xunyuji\\test_case\\conftest.py\", line 23, in login\n    r = method.main_way('get', url=url_home, headers=header)\n  File \"D:\\Atest_project\\requests_pytest_xunyuji\\util\\method.py\", line 24, in main_way\n    res = self.get_way(url, data, headers, cookies)\n  File \"D:\\Atest_project\\requests_pytest_xunyuji\\util\\method.py\", line 14, in get_way\n    res = requests.get(url=url, params=params, headers=headers, cookies=cookies, verify=False)\n  File \"d:\\python37\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"d:\\python37\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"d:\\python37\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"d:\\python37\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"d:\\python37\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1587118955428, "stop": 1587118955428}], "start": 1587118955428, "stop": 1587118955678}